### ISSUE TITLE
Doesn't Work- defined_sensor paramter missing

### ISSUE THREAD

**Issue by recrudesce** [EiNSTeiN-/roadrunner-filament-sensor#14]
If I add the configuration as per the documentation I get the following error

```
Internal error during connect: __init__() missing 1 required positional argument: 'defined_sensor'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
```

The klippy log shows as follows:
```
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 279, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 214, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 198, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/high_resolution_filament_sensor.py", line 988, in load_config_prefix
    return HighResolutionFilamentSensor(config)
  File "/home/pi/klipper/klippy/extras/high_resolution_filament_sensor.py", line 534, in __init__
    self.runout_helper = RunoutHelper(config, self)
  File "/home/pi/klipper/klippy/extras/high_resolution_filament_sensor.py", line 519, in __init__
    super().__init__(config)
TypeError: __init__() missing 1 required positional argument: 'defined_sensor'
```

I cannot find anything in the code that references `defined_sensor`

I am running the latest version of Kalico.

**Comment by recrudesce** [comment]
OK, this requires the following changes to fix for Kalico:

Line 519 needs to be changed to
`super().__init__(config, sensor)`

so the whole `RunoutHelper` class reads as follows:
```
class RunoutHelper(filament_switch_sensor.RunoutHelper):
    def __init__(self, config, sensor):
        super().__init__(config, sensor)
        self._sensor = sensor
```

then Klipper service needs restarting
